# Generated by Django 3.0.7 on 2020-07-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.CharField(max_length=225)),
                ('card2', models.CharField(max_length=225)),
                ('card3', models.CharField(max_length=225)),
                ('card4', models.CharField(max_length=225)),
                ('card5', models.CharField(max_length=225)),
                ('card6', models.CharField(max_length=225)),
                ('card7', models.CharField(max_length=225)),
                ('card8', models.CharField(max_length=225)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='announceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('pageview', models.IntegerField()),
                ('content', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
