# Generated by Django 3.0.7 on 2020-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendarTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('start', models.TextField(blank=True)),
                ('end', models.TextField(blank=True)),
                ('backgroundColor', models.TextField(blank=True)),
                ('borderColor', models.TextField(blank=True)),
                ('allDay', models.TextField(blank=True)),
            ],
        ),
    ]
