# Generated by Django 3.0.7 on 2020-07-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0002_calendartable'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartable',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
