# Generated by Django 3.0.7 on 2020-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0003_calendartable_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartable',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
