# Generated by Django 3.0.7 on 2020-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0004_calendartable_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartable',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
