# Generated by Django 3.0.7 on 2020-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0005_calendartable_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartable',
            name='urlForStu',
            field=models.TextField(blank=True),
        ),
    ]
