# Generated by Django 3.0.7 on 2020-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0006_calendartable_urlforstu'),
    ]

    operations = [
        migrations.CreateModel(
            name='clockinTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField()),
                ('name', models.TextField()),
                ('checkin', models.DateField(blank=True)),
                ('checkout', models.DateField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('shouldin', models.DateField(blank=True)),
                ('shouldout', models.DateField(blank=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='dailyStateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('fromTime', models.DateField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='leaveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitTime', models.DateField()),
                ('name', models.TextField()),
                ('fromTime', models.DateField()),
                ('toTime', models.DateField()),
                ('state', models.TextField()),
                ('content', models.DateField(blank=True)),
                ('check', models.DateField(blank=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
