# Generated by Django 3.0.7 on 2020-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0008_groupaccounttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupCode', models.TextField()),
                ('name', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
