# Generated by Django 3.0.7 on 2020-08-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0009_grouptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcetable',
            name='group',
            field=models.TextField(blank=True),
        ),
    ]
