# Generated by Django 3.0.7 on 2020-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0010_announcetable_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcecard',
            name='group',
            field=models.TextField(blank=True),
        ),
    ]
