# Generated by Django 3.0.7 on 2020-08-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0011_announcecard_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartable',
            name='group',
            field=models.TextField(blank=True),
        ),
    ]
