# Generated by Django 3.0.7 on 2020-08-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0013_auto_20200805_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockintable',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockintable',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockintable',
            name='isDelete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clockintable',
            name='shouldin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockintable',
            name='shouldout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockintable',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
